// Autogenerated from Pigeon (v0.2.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTSearchReply;
@class FLTSearchRequest;

@interface FLTSearchReply : NSObject
@property(nonatomic, copy, nullable) NSString * result;
@end

@interface FLTSearchRequest : NSObject
@property(nonatomic, copy, nullable) NSString * query;
@end

@protocol FLTApi
-(nullable FLTSearchReply *)search:(FLTSearchRequest*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTApi> _Nullable api);

NS_ASSUME_NONNULL_END
